// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using MyHomeProject.Models;
using System;

namespace MyHomeProject.Migrations
{
    [DbContext(typeof(MyHomeProjectContext))]
    [Migration("20180724113144_pls help me")]
    partial class plshelpme
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.3-rtm-10026")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("MyHomeProject.Models.Dish", b =>
                {
                    b.Property<int>("DishID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Category");

                    b.Property<string>("Recipe");

                    b.Property<string>("Title");

                    b.HasKey("DishID");

                    b.ToTable("Dishes");
                });

            modelBuilder.Entity("MyHomeProject.Models.Dish_Ingrident", b =>
                {
                    b.Property<int>("DishId");

                    b.Property<int>("IngridientId");

                    b.HasKey("DishId", "IngridientId");

                    b.HasIndex("IngridientId");

                    b.ToTable("Dish_Ingridents");
                });

            modelBuilder.Entity("MyHomeProject.Models.Ingridient", b =>
                {
                    b.Property<int>("IngridientId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("title");

                    b.HasKey("IngridientId");

                    b.ToTable("Ingridients");
                });

            modelBuilder.Entity("MyHomeProject.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Email");

                    b.Property<string>("Password");

                    b.HasKey("UserId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("MyHomeProject.Models.Dish_Ingrident", b =>
                {
                    b.HasOne("MyHomeProject.Models.Dish", "Dish")
                        .WithMany("Dish_Ingridients")
                        .HasForeignKey("DishId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("MyHomeProject.Models.Ingridient", "Ingridient")
                        .WithMany("Dish_Ingridients")
                        .HasForeignKey("IngridientId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
